library(DESeq2)
counts <- read.csv('counts.csv', row.names=1)
coldata <- read.csv('coldata.csv', row.names=1)
dds <- DESeqDataSetFromMatrix(countData=counts, colData=coldata, design=~condition)
dds <- DESeq(dds)
res <- results(dds)
head(res[order(res$pvalue),])
